### ISSUE TITLE
Highlight Drop Statement

### ISSUE THREAD

**Issue by cmendesfirmino** [Gimly/vscode-qlik#2]
Hi, I've just notice that the drop statment is not too correct. Drop table and Drop Field are ok but Drop Tables and Drop Fields. I read the code qvs.tmLanguage and made a correction.

```
<key>comment</key>
<string>DROP statement</string>
<key>match</key>
<string>(?i:^\s*(drop)\s+(table[s]?|field[s]?))</string>
<key>name</key>
<string>meta.drop.qvs</string>
```
There are some highlights to correct too like RENAME, DO UNTIL ... LOOP, INNER JOIN, RIGHT JOIN, OUTER JOIN.

Thanks

**Comment by Gimly** [comment]
Hi @cmendesfirmino thanks for the heads-up! Since you already did the change, you can create a pull request and I'll happily merge it, this way I don't "steal" your work 😄 and you'll be a contributor.

**Comment by cmendesfirmino** [comment]
Hi @Gimly, so I gonna to make these improviments before pull request. I'm glad to contribute with this helpful project.

Thanks
