### ISSUE TITLE
Can't install on Visual Studio 2019

### ISSUE THREAD

**Issue by enrique** [Gimly/vscode-qlik#8]
Can you add support for Visual Studio 2019?

This is the log while installing:

4/14/2020 4:55:42 PM - Microsoft VSIX Installer
4/14/2020 4:55:42 PM - -------------------------------------------
4/14/2020 4:55:42 PM - vsixinstaller.exe version:
4/14/2020 4:55:42 PM - 16.2.3073
4/14/2020 4:55:42 PM - -------------------------------------------
4/14/2020 4:55:42 PM - Command line parameters:
4/14/2020 4:55:42 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\USER\Downloads\Gimly81.qlik-0.5.0.vsix
4/14/2020 4:55:42 PM - -------------------------------------------
4/14/2020 4:55:42 PM - Microsoft VSIX Installer
4/14/2020 4:55:42 PM - -------------------------------------------
4/14/2020 4:55:43 PM - Initializing Install...
4/14/2020 4:55:43 PM - Extension Details...
4/14/2020 4:55:43 PM - 	Identifier         : qlik
4/14/2020 4:55:43 PM - 	Name               : Qlik
4/14/2020 4:55:43 PM - 	Author             : Gimly81
4/14/2020 4:55:43 PM - 	Version            : 0.5.0
4/14/2020 4:55:43 PM - 	Description        : Qlik script support for Visual Studio Code
4/14/2020 4:55:43 PM - 	Locale             : en-US
4/14/2020 4:55:43 PM - 	MoreInfoURL        : 
4/14/2020 4:55:43 PM - 	InstalledByMSI     : False
4/14/2020 4:55:43 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
4/14/2020 4:55:43 PM - 
4/14/2020 4:55:43 PM - 	SignatureState     : Unsigned
4/14/2020 4:55:43 PM - 	Supported Products : 
4/14/2020 4:55:43 PM - 		Microsoft.VisualStudio.Code
4/14/2020 4:55:43 PM - 			Version : 
4/14/2020 4:55:43 PM - 
4/14/2020 4:55:43 PM - 	References         : 
4/14/2020 4:55:43 PM - Signature Details...
4/14/2020 4:55:43 PM - 	Extension is not signed.
4/14/2020 4:55:43 PM - 
4/14/2020 4:55:43 PM - Searching for applicable products...
4/14/2020 4:55:43 PM - Found installed product - Global Location
4/14/2020 4:55:43 PM - Found installed product - Visual Studio Professional 2019
4/14/2020 4:55:44 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Gimly** [comment]
How did you download a VSIX for that extension? This is an extension for Visual Studio Code, and not for Visual Studio 2019. As far as I know, VS Code and VS 2019 extensions are very different, if I was to make one for VS 2019 it would be in another repository.

**Comment by Gimly** [comment]
Closing since I didn't get any info back
